name: Test Nix Flake

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x86_64, aarch64]

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27  # https://github.com/cachix/install-nix-action
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix flake update
    - run: nix develop .#dev.test --command fastfetch
